name: 'Manual Terraform Destroy'

on:
  # Allows manual running from the GitHub Actions UI
  workflow_dispatch:
    inputs:
      # Input for selecting the target environment/folder to destroy
      environment:
        description: 'Target Environment Folder to DESTROY'
        type: choice
        required: true
        default: dev
        options:
          - dev
          # You can add other environments (e.g., staging) here

# Defines a single job named 'terraform-destroy'
jobs:
  terraform-destroy:
    name: 'Terraform Destroy - ${{ github.event.inputs.environment }}'
    runs-on: ubuntu-latest
    
    # Set the working directory dynamically based on user input
    defaults:
      run:
        working-directory: environments/${{ github.event.inputs.environment }}

    # Map the GitHub Secrets to environment variables for Azure authentication
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          # Use a version compatible with your current deployment
          terraform_version: 1.6.x 

      # 1. Terraform Init (Pulls remote state file)
      - name: Terraform Init (Load Remote State)
        run: terraform init

      # 2. Terraform Destroy Plan (Show what will be destroyed)
      - name: Terraform Destroy Plan
        id: destroy_plan
        run: terraform plan -destroy -no-color -out=destroyplan -lock-timeout=15m

      # 3. Confirmation and Apply (Final step to delete resources)
      - name: Terraform Destroy Apply
        id: destroy
        # The '-auto-approve' flag ensures it runs without human confirmation inside the workflow.
        # This is typically acceptable for a manually triggered destroy job.
        run: terraform force-unlock de5520ce-d225-5b81-f1f3-b21df15a1925
        run: terraform destroy -auto-approve
        
